version:     "`r format(Sys.time(), '%d %B, %Y')`"
copyright:   "2022"
author:      "ARK"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/fabianark/os222/"
myloglink:   "/TXT/mylog.txt"
mypublickey: "/TXT/mypubkey.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
